name: Daily deploy to CF Pages

on:
  workflow_dispatch:
  # Deploy once every day
  schedule:
    - cron: "0 0 * * *"

jobs:
  deploy-cloudflare-pages:
    name: Daily deploy to CF Pages
    runs-on: ubuntu-latest
    env:
      CF_BRANCH: master
      cloudflare_website: balenacloud-docs

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65
        with:
          node-version: 22
          cache: "npm"

      - name: Build docs
        run: npm run deploy-docs --if-present

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@a84dcc6dd36c8769fbff7e622308c8050fc41f4f # v3.5.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          wranglerVersion: '4.19.1' # latest - https://www.npmjs.com/package/wrangler
          command: --version
          postCommands: npx wrangler pages deploy --branch $CF_BRANCH --project-name=$cloudflare_website  build/ | tee -a $GITHUB_STEP_SUMMARY
